# Generated by Django 3.0.5 on 2020-04-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_auto_20200416_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='entregado',
        ),
    ]
